"use client";

import {
  BookOpen,
  Coins,
  Flame,
  type LucideIcon,
  Network,
  Search,
  Sparkles,
} from "lucide-react";
import { useMemo, useState } from "react";
import { Footer } from "@/components/layout";

interface Term {
  term: string;
  definition: string;
  category: "protocol" | "blockchain" | "economy";
}

type CategoryFilterValue = Term["category"] | "all";

const TERMS: Term[] = [
  // Protocol
  {
    term: "ScorchCore",
    definition:
      "The burning heart of the protocol — a primordial energy source discovered deep within the Forgotten Rifts of Lunacia. It powers the entire Forge & Collect-to-Earn ecosystem.",
    category: "protocol",
  },
  {
    term: "CoreMiner",
    definition:
      "An NFT born from the Elemental Forge. CoreMiners are created by transmuting dormant Axies and passively mine $CORE tokens based on their stats and type.",
    category: "protocol",
  },
  {
    term: "Geode",
    definition:
      "A Crystalline Geode NFT created during the Forge process. It incubates before hatching into a CoreMiner with randomized stats and rarity.",
    category: "protocol",
  },
  {
    term: "Elemental Forge",
    definition:
      "The core mechanism of the protocol. Select dormant Axies, add SLP and resources, and transmute them into Crystalline Geodes that hatch into CoreMiners.",
    category: "protocol",
  },
  {
    term: "Resonance Power",
    definition:
      "A passive bonus generated by staking Axies in the protocol. Higher Resonance Power increases mining efficiency for your CoreMiners.",
    category: "protocol",
  },
  {
    term: "TrustScore",
    definition:
      "A reputation metric that tracks player behavior and engagement. Higher TrustScore unlocks better mining rates and protocol benefits.",
    category: "protocol",
  },
  {
    term: "Set Bonus",
    definition:
      "A permanent bonus earned by collecting specific combinations of CoreMiners. Complete sets grant additional mining power and unique rewards.",
    category: "protocol",
  },
  {
    term: "Memento",
    definition:
      "A consumable item used during the Forge process to guarantee success or improve the odds of hatching rare CoreMiners.",
    category: "protocol",
  },
  {
    term: "Hatching",
    definition:
      "The process of opening a Geode to reveal the CoreMiner inside. Each Geode has 7 possible CoreMiner outcomes per type, with a 1% chance of a Critical (rare) result.",
    category: "protocol",
  },
  {
    term: "Mining Cycle",
    definition:
      "A timed period during which a CoreMiner is locked and actively mining $CORE. Longer cycles yield higher rewards but lock the miner for more time.",
    category: "protocol",
  },
  {
    term: "Prospector",
    definition:
      "Any player participating in the ScorchCore Protocol — forging CoreMiners, mining $CORE, and contributing to the ecosystem.",
    category: "protocol",
  },
  // Economy
  {
    term: "$CORE",
    definition:
      "The native utility token of ScorchCore Protocol with a hard cap of 2.1 Billion tokens. Used for upgrades, repairs, governance, and staking. Follows an annual halving emission schedule.",
    category: "economy",
  },
  {
    term: "$fCORE",
    definition:
      "Fractional CORE — a non-transferable token representing unmined $CORE rewards. Must be converted to $CORE through the Proof-of-Humanity verification process.",
    category: "economy",
  },
  {
    term: "Halving",
    definition:
      "An annual event that cuts the $CORE emission rate by 50%, creating programmed scarcity similar to Bitcoin's halving mechanism.",
    category: "economy",
  },
  {
    term: "Burn-to-Earn",
    definition:
      "The core economic model: dormant Axies are burned (transmuted) to create CoreMiners, permanently reducing Axie supply while generating new productive assets.",
    category: "economy",
  },
  {
    term: "Vesting",
    definition:
      "A time-locked token release schedule. Team and treasury $CORE allocations are vested over time to ensure long-term alignment.",
    category: "economy",
  },
  {
    term: "Buyback",
    definition:
      "A protocol mechanism that uses treasury funds to purchase $CORE from the open market, supporting token price and reducing circulating supply.",
    category: "economy",
  },
  // Blockchain
  {
    term: "Ronin",
    definition:
      "An EVM-compatible blockchain built by Sky Mavis specifically for gaming. ScorchCore Protocol is deployed on Ronin for fast, low-cost transactions.",
    category: "blockchain",
  },
  {
    term: "Wallet",
    definition:
      "A digital account that holds your tokens and NFTs on the blockchain. ScorchCore uses the Ronin Waypoint wallet for seamless authentication.",
    category: "blockchain",
  },
  {
    term: "NFT (Non-Fungible Token)",
    definition:
      "A unique digital asset on the blockchain. In ScorchCore, CoreMiners and Geodes are NFTs with distinct properties and ownership.",
    category: "blockchain",
  },
  {
    term: "Smart Contract",
    definition:
      "Self-executing code on the blockchain that powers all protocol operations — forging, mining, staking, and token distribution — without intermediaries.",
    category: "blockchain",
  },
  {
    term: "Staking",
    definition:
      "Locking tokens or NFTs in a smart contract to earn rewards. In ScorchCore, staking Axies generates Resonance Power.",
    category: "blockchain",
  },
  {
    term: "Gas Fee",
    definition:
      "A small transaction fee paid to process operations on the blockchain. Ronin's low gas fees make ScorchCore accessible to all players.",
    category: "blockchain",
  },
  {
    term: "Mint",
    definition:
      "The process of creating a new token or NFT on the blockchain. When a Geode hatches, a new CoreMiner NFT is minted.",
    category: "blockchain",
  },
  {
    term: "Burn",
    definition:
      "Permanently destroying a token or NFT by sending it to an irrecoverable address. Burning is central to the Forge transmutation process.",
    category: "blockchain",
  },
];

const CATEGORY_META: Record<
  Term["category"],
  {
    label: string;
    icon: LucideIcon;
    accent: string;
    border: string;
    glow: string;
  }
> = {
  protocol: {
    label: "Protocol",
    icon: Flame,
    accent: "text-magma-gold",
    border: "border-magma-gold/45",
    glow: "from-orange-500/26 to-yellow-300/8",
  },
  economy: {
    label: "Economy",
    icon: Coins,
    accent: "text-ethereal-cyan",
    border: "border-ethereal-cyan/45",
    glow: "from-cyan-300/22 to-blue-500/8",
  },
  blockchain: {
    label: "Blockchain",
    icon: Network,
    accent: "text-magma-orange",
    border: "border-orange-400/45",
    glow: "from-orange-600/20 to-cyan-300/8",
  },
};

const FILTERS: Array<{
  value: CategoryFilterValue;
  label: string;
  icon: LucideIcon;
}> = [
  { value: "all", label: "All", icon: BookOpen },
  { value: "protocol", label: CATEGORY_META.protocol.label, icon: Flame },
  { value: "economy", label: CATEGORY_META.economy.label, icon: Coins },
  { value: "blockchain", label: CATEGORY_META.blockchain.label, icon: Network },
];

function getCategoryCount(category: CategoryFilterValue) {
  if (category === "all") return TERMS.length;
  return TERMS.filter((term) => term.category === category).length;
}

function TerminologyHero({ total }: { total: number }) {
  return (
    <header className="mx-auto max-w-4xl text-center">
      <p className="alchemy-eyebrow mb-4 text-xs">ScorchCore Lexicon</p>
      <h1 className="alchemy-heading-strong text-balance text-4xl leading-tight md:text-6xl">
        Terminology
      </h1>
      <p className="alchemy-copy mx-auto mt-5 max-w-2xl text-pretty text-sm leading-7 text-white/72 md:text-base">
        A field guide to the protocol language behind dormant assets, alchemical
        forging, CoreMiner production, and the $CORE economy.
      </p>
      <div className="mx-auto mt-7 flex w-fit items-center gap-2 border border-ethereal-cyan/25 bg-black/35 px-4 py-2 text-xs text-cyan-50/70 shadow-[0_0_24px_rgba(125,249,255,0.08)]">
        <Sparkles className="h-3.5 w-3.5 text-ethereal-cyan" />
        <span>{total} indexed terms</span>
      </div>
    </header>
  );
}

function TerminologySearch({
  search,
  onSearchChange,
}: {
  search: string;
  onSearchChange: (value: string) => void;
}) {
  return (
    <label className="group relative block">
      <span className="sr-only">Search terminology</span>
      <Search className="pointer-events-none absolute left-5 top-1/2 h-5 w-5 -translate-y-1/2 text-ethereal-cyan/70 transition-colors group-focus-within:text-magma-gold" />
      <input
        type="search"
        aria-label="Search terminology"
        placeholder="Search terms, systems, tokens..."
        value={search}
        onChange={(event) => onSearchChange(event.target.value)}
        className="alchemy-copy h-14 w-full border border-ethereal-cyan/25 bg-black/48 px-14 text-sm text-cyan-50 shadow-[inset_0_0_24px_rgba(125,249,255,0.05),0_0_30px_rgba(0,0,0,0.45)] outline-none transition-all placeholder:text-cyan-50/32 focus:border-magma-gold/70 focus:shadow-[inset_0_0_28px_rgba(247,198,90,0.08),0_0_34px_rgba(240,106,18,0.16)]"
      />
    </label>
  );
}

function CategoryFilter({
  activeCategory,
  onCategoryChange,
}: {
  activeCategory: CategoryFilterValue;
  onCategoryChange: (category: CategoryFilterValue) => void;
}) {
  return (
    <fieldset className="flex flex-wrap gap-2">
      <legend className="sr-only">Filter terminology categories</legend>
      {FILTERS.map((filter) => {
        const Icon = filter.icon;
        const isActive = activeCategory === filter.value;
        return (
          <button
            key={filter.value}
            type="button"
            aria-pressed={isActive}
            onClick={() => onCategoryChange(filter.value)}
            className={`inline-flex min-h-11 items-center gap-2 border px-4 py-2 text-xs font-semibold uppercase transition-all focus:outline-none focus-visible:ring-2 focus-visible:ring-cyan-300/75 focus-visible:ring-offset-2 focus-visible:ring-offset-black ${
              isActive
                ? "border-magma-gold/70 bg-orange-500/14 text-magma-gold shadow-[0_0_26px_rgba(240,106,18,0.18)]"
                : "border-cyan-100/12 bg-black/42 text-cyan-50/58 hover:border-ethereal-cyan/45 hover:text-cyan-50"
            }`}
          >
            <Icon className="h-4 w-4" />
            <span>{filter.label}</span>
            <span className="text-cyan-50/42">
              {getCategoryCount(filter.value)}
            </span>
          </button>
        );
      })}
    </fieldset>
  );
}

function TermCard({ item }: { item: Term }) {
  const meta = CATEGORY_META[item.category];
  const Icon = meta.icon;

  return (
    <article
      className={`group relative overflow-hidden border ${meta.border} bg-black/42 p-5 shadow-[0_18px_50px_rgba(0,0,0,0.34)] backdrop-blur-md transition-all hover:-translate-y-0.5 hover:border-magma-gold/55 hover:shadow-[0_22px_60px_rgba(0,0,0,0.46)]`}
    >
      <div
        className={`pointer-events-none absolute inset-0 bg-gradient-to-br ${meta.glow} opacity-70 transition-opacity group-hover:opacity-100`}
      />
      <div className="pointer-events-none absolute left-0 top-0 h-full w-px bg-gradient-to-b from-transparent via-magma-gold/70 to-transparent" />

      <div className="relative flex gap-4">
        <div className="flex h-11 w-11 shrink-0 items-center justify-center border border-cyan-100/14 bg-black/50 shadow-[0_0_22px_rgba(125,249,255,0.08)]">
          <Icon className={`h-5 w-5 ${meta.accent}`} />
        </div>
        <div className="min-w-0">
          <div className="mb-3 flex flex-wrap items-center gap-2">
            <h2 className="alchemy-heading text-xl leading-tight">
              {item.term}
            </h2>
            <span className="border border-cyan-100/12 bg-black/42 px-2.5 py-1 text-[0.65rem] font-semibold uppercase tracking-[0.18em] text-cyan-50/52">
              {meta.label}
            </span>
          </div>
          <p className="alchemy-copy text-sm leading-7 text-cyan-50/72">
            {item.definition}
          </p>
        </div>
      </div>
    </article>
  );
}

function EmptyTerminologyState({ search }: { search: string }) {
  return (
    <div className="border border-orange-300/20 bg-black/42 px-6 py-14 text-center shadow-[0_0_36px_rgba(240,106,18,0.08)]">
      <BookOpen className="mx-auto mb-4 h-8 w-8 text-magma-gold" />
      <h2 className="alchemy-heading mb-3 text-2xl">No matching terms</h2>
      <p className="alchemy-copy mx-auto max-w-md text-sm leading-6 text-cyan-50/62">
        No entries matched "{search}". Try a protocol name, token symbol, or
        blockchain operation.
      </p>
    </div>
  );
}

export default function TerminologyPage() {
  const [search, setSearch] = useState("");
  const [activeCategory, setActiveCategory] =
    useState<CategoryFilterValue>("all");

  const filtered = useMemo(() => {
    const normalizedSearch = search.trim().toLowerCase();

    return TERMS.filter((term) => {
      const matchesSearch =
        normalizedSearch === "" ||
        term.term.toLowerCase().includes(normalizedSearch) ||
        term.definition.toLowerCase().includes(normalizedSearch);
      const matchesCategory =
        activeCategory === "all" || term.category === activeCategory;
      return matchesSearch && matchesCategory;
    });
  }, [activeCategory, search]);

  return (
    <>
      <main className="alchemy-copy relative min-h-screen overflow-hidden bg-deep-abyss pt-28 text-white">
        <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_50%_8%,rgba(125,249,255,0.16),transparent_30%),radial-gradient(circle_at_22%_32%,rgba(240,106,18,0.14),transparent_28%),linear-gradient(180deg,#020607_0%,#030b0e_48%,#010203_100%)]" />
        <div className="pointer-events-none absolute inset-0 bg-[linear-gradient(90deg,rgba(0,0,0,0.78),transparent_20%,transparent_80%,rgba(0,0,0,0.78)),radial-gradient(ellipse_at_center,transparent_0_42%,rgba(0,0,0,0.58)_100%)]" />

        <div className="relative z-[1] mx-auto w-full max-w-6xl px-4 pb-20 md:px-8">
          <TerminologyHero total={TERMS.length} />

          <section className="mx-auto mt-10 max-w-4xl space-y-4 border border-cyan-100/10 bg-black/30 p-4 shadow-[0_24px_80px_rgba(0,0,0,0.38)] backdrop-blur-md md:p-5">
            <TerminologySearch search={search} onSearchChange={setSearch} />
            <CategoryFilter
              activeCategory={activeCategory}
              onCategoryChange={setActiveCategory}
            />
          </section>

          <section className="mt-10">
            {filtered.length === 0 ? (
              <EmptyTerminologyState search={search} />
            ) : (
              <div className="grid gap-4 lg:grid-cols-2">
                {filtered.map((item) => (
                  <TermCard key={item.term} item={item} />
                ))}
              </div>
            )}
          </section>
        </div>
      </main>
      <Footer />
    </>
  );
}
